### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Parniaan** [DavisPL/PCCC#10]
- [ ] Use CodeSearchNet python examples and Dafny-of-Python to convert python functions blocks to Dafny
- [ ] Add examples from program proofs

**Comment by Parniaan** [comment]
Updated:


- [x] Add more filesystem scenarios to tests
- [x] Use Mitre CWE cases
- [ ] Add proper JSON for dataset
- [ ] All Filesystem.dfy files should have same functions and methods (check before finalizing the filesystem)
