### ISSUE TITLE
Proofs for Files in Fileio library

### ISSUE THREAD

**Issue by Parniaan** [DavisPL/PCCC#2]
- [x] Add preconditions to proof file access into fileio.dfy library
- [x] Check verification of  fileiotest.dy with the proofs added to filestream
- [x] Add a test case for reading from a file
- [x] Add a test case for writing to a file
